name: covid19italia
description: COVID-19 Italia - Monitoraggio situazione

version: 1.5.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  provider: any
  flutter_map: any
  flutter_map_marker_cluster: any
  http: any
#  charts_flutter: any
  syncfusion_flutter_charts: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - syncfusion.lic

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/covid19.png"
